### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by nasok-ess** [KizhiFox/token-sheet-generator#1]
When i press export as PDF loading starts and then just never ends.

**Comment by KizhiFox** [comment]
@nasok-ess could you please download your sheet as JSON (via "Save project" button) and send it to me?

**Comment by KizhiFox** [comment]
@nasok-ess and could you tell me which browser and OS are you using?

**Comment by nasok-ess** [comment]
Sorry for bothering you, but i already know what was wrong. My stupid uploaded a .webp file and that's why it didn't work.

**Comment by KizhiFox** [comment]
@nasok-ess okay. In fact at one point I wanted to add WebP support, but it was too tedious and too infrequent in use. Thank you for using this generator :)

**Comment by KizhiFox** [comment]
@nasok-ess I've added WebP support :)
