### ISSUE TITLE
Add option for 'gap between tokens'

### ISSUE THREAD

**Issue by nmeier** [KizhiFox/token-sheet-generator#2]
Great app, easy to use. One option I would like to have is 'gap between tokens'. My hole punch doesn't like to cut with only a tiny sliver of paper left. I would like to add an inch between neighboring tokens.

**Comment by nmeier** [comment]
added pull request https://github.com/KizhiFox/token-sheet-generator/compare/main...nmeier:token-sheet-generator:main

**Comment by KizhiFox** [comment]
Oh that's a neat feature you've added! I'll add translation to my native language and update the README file soon (today or tomorrow) and after that I will merge your pull request

**Comment by KizhiFox** [comment]
Thank you!

**Comment by KizhiFox** [comment]
@nmeier can you show me what you use to cut out the tokens? Just wondering :)

**Comment by nmeier** [comment]
it's a [EK 1 inch hole punch](https://www.amazon.com/EK-Handmade-Scrapbooking-Invitations-Decorations/dp/B00C90WM14?th=1). Works pretty well, just struggles if there's not enough paper in between cut outs.

**Comment by KizhiFox** [comment]
Wow! I didn't know such things existed! I bought myself one of these
